-- FreshCart Sprint 2 PostgreSQL schema
-- Extends Sprint 1 entities and adds catalog foundation.

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'customer' CHECK (role IN ('customer','admin')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id INTEGER NULL REFERENCES categories(id) ON UPDATE CASCADE ON DELETE SET NULL,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(140) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INTEGER NOT NULL REFERENCES categories(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  name VARCHAR(180) NOT NULL,
  slug VARCHAR(200) NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  status VARCHAR(20) NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS variants (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON UPDATE CASCADE ON DELETE CASCADE,
  name VARCHAR(120) NOT NULL,
  option_values JSONB NOT NULL DEFAULT '{}'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(product_id, name)
);

CREATE TABLE IF NOT EXISTS skus (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON UPDATE CASCADE ON DELETE CASCADE,
  variant_id INTEGER NULL REFERENCES variants(id) ON UPDATE CASCADE ON DELETE CASCADE,
  sku_code VARCHAR(80) NOT NULL UNIQUE,
  price DECIMAL(12,2) NOT NULL CHECK (price >= 0),
  stock_quantity INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sku_variant_product_match CHECK (variant_id IS NULL OR product_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS carts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cart_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cart_id INTEGER NOT NULL REFERENCES carts(id) ON UPDATE CASCADE ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  sku_id INTEGER NULL REFERENCES skus(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  UNIQUE(cart_id, sku_id)
);

CREATE TABLE IF NOT EXISTS orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  total_amount DECIMAL(12,2) NOT NULL CHECK (total_amount >= 0),
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(id) ON UPDATE CASCADE ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  sku_id INTEGER NOT NULL REFERENCES skus(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price DECIMAL(12,2) NOT NULL CHECK (unit_price >= 0)
);

CREATE TABLE IF NOT EXISTS assets (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id INTEGER NULL REFERENCES products(id) ON UPDATE CASCADE ON DELETE CASCADE,
  variant_id INTEGER NULL REFERENCES variants(id) ON UPDATE CASCADE ON DELETE CASCADE,
  storage_key VARCHAR(500) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'gallery',
  alt_text VARCHAR(255) NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
  CONSTRAINT asset_owner_check CHECK (product_id IS NOT NULL OR variant_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS product_specifications (
  product_id INTEGER PRIMARY KEY REFERENCES products(id) ON UPDATE CASCADE ON DELETE CASCADE,
  specifications JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_products_category_id ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_variants_product_id ON variants(product_id);
CREATE INDEX IF NOT EXISTS idx_skus_product_id ON skus(product_id);
CREATE INDEX IF NOT EXISTS idx_skus_variant_id ON skus(variant_id);

-- A SKU variant must belong to the same product as the SKU.
CREATE OR REPLACE FUNCTION validate_sku_variant_product() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.variant_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM variants v WHERE v.id = NEW.variant_id AND v.product_id = NEW.product_id) THEN
    RAISE EXCEPTION 'variant does not belong to SKU product';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS sku_variant_product_guard ON skus;
CREATE TRIGGER sku_variant_product_guard
BEFORE INSERT OR UPDATE OF product_id, variant_id ON skus
FOR EACH ROW EXECUTE FUNCTION validate_sku_variant_product();
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);

-- PostgreSQL trigger prevents a category from becoming its own ancestor.
CREATE OR REPLACE FUNCTION prevent_category_cycle() RETURNS TRIGGER AS $$
DECLARE
  cursor_id INTEGER;
  seen_ids INTEGER[] := ARRAY[]::INTEGER[];
BEGIN
  IF NEW.parent_id IS NULL THEN RETURN NEW; END IF;
  IF NEW.parent_id = NEW.id THEN RAISE EXCEPTION 'category cannot be its own parent'; END IF;
  cursor_id := NEW.parent_id;
  WHILE cursor_id IS NOT NULL LOOP
    IF cursor_id = NEW.id THEN RAISE EXCEPTION 'category hierarchy cycle detected'; END IF;
    IF cursor_id = ANY(seen_ids) THEN EXIT; END IF;
    seen_ids := array_append(seen_ids, cursor_id);
    SELECT parent_id INTO cursor_id FROM categories WHERE id = cursor_id;
  END LOOP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS categories_cycle_guard ON categories;
CREATE TRIGGER categories_cycle_guard
BEFORE INSERT OR UPDATE OF parent_id ON categories
FOR EACH ROW EXECUTE FUNCTION prevent_category_cycle();
